apiVersion: v1
kind: Pod
metadata:
  name: cachepod
  labels:
    app: backend
spec:
  containers:
    - name: flightcache
      image: flightcache
      imagePullPolicy: Never
    - name: redis
      image: redis
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 6379  # Default Redis port