# https://kubernetes.io/docs/concepts/workloads/pods/
apiVersion: v1
kind: Pod
metadata:
  name: providermanagerpod
  labels:
    app: backend
spec:
  containers:
    - name: providermanager
      image: providermanager
      imagePullPolicy: Never
    - name: redis
      image: redis
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 6379  # Default Redis port