# https://kubernetes.io/docs/concepts/workloads/pods/
apiVersion: v1
kind: Pod
metadata:
  name: reprocessor
  labels:
    app: reprocessor
spec:
  containers:
    - name: reprocessor
      image: reprocessor
      imagePullPolicy: Never
      ports:
        - containerPort: 5111
