# https://kubernetes.io/docs/concepts/workloads/pods/
apiVersion: v1
kind: Pod
metadata:
  name: searchagentpod
  labels:
    app: backend
spec:
  containers:
    - name: searchagent
      image: searchagent
      imagePullPolicy: Never
    - name: hashcalculator
      image: hashcalculator
      imagePullPolicy: Never
    - name: redis
      image: redis
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 6379  # Default Redis port
