# https://kubernetes.io/docs/concepts/workloads/pods/
apiVersion: v1
kind: Pod
metadata:
  name: searchersimulatorpod
  labels:
    app: backend
spec:
  containers:
    - name: searchersimulator
      image: searchersimulator
      imagePullPolicy: Never
