# https://kubernetes.io/docs/concepts/workloads/pods/
apiVersion: v1
kind: Pod
metadata:
  name: providermanagerpod2
  labels:
    app: backend
spec:
  containers:
    - name: providermanager
      image: providermanager
      imagePullPolicy: Never
      env:
        - name: PROVIDER_ID
          value: "2"
        - name: PROVIDER_ADDRESS
          value: "http://192.168.178.98:81/mock/search/"
        - name: PROVIDER_NAME
          value: "megaflight24"
        - name: PROVIDER_MAX_RESULTS
          value: "100"
        - name: PROVIDER_TTL
          value: "120"
    - name: redis
      image: redis
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 6379 # Default Redis port
