# https://kubernetes.io/docs/concepts/workloads/pods/
apiVersion: v1
kind: Pod
metadata:
  name: "frontpod"
  labels:
    app: "frontend"
spec:
  containers:
  - name: website
    image: "website"
    imagePullPolicy: Never
