# https://kubernetes.io/docs/concepts/workloads/pods/
apiVersion: v1
kind: Pod
metadata:
  name: frontpod
  labels:
    app: webserver
spec:
  containers:
  - name: website
    image: website
    imagePullPolicy: Never
    ports:
      - containerPort: 5101
  - name: searchorderserver
    image: sos
    imagePullPolicy: Never
    ports:
      - containerPort: 5001

